### PR TITLE
Moving the EA filter query to request URL instead of building it on t…

### PR DESCRIPTION
**Pull request by chinmayb**
…he payload body

    * Currently the EA filters are passed as api payload, this is creating
      problem when the obj is empty and ea is requested in GET call. Hence
      moving it as URL parameter.

      `objJSON = append(append(objJSON[:len(objJSON)-1], byte(',')), eaSearchJSON[1:]...)`

    * Add Get A record call

### CODE REVIEW

**Comment by yuewko** [comment]
I assume this PR is to address https://github.com/infobloxopen/infoblox-go-client/issues/48. If so, please indicate accordingly in the description.

Please refer to https://github.com/infobloxopen/infoblox-go-client/issues/48#issuecomment-378324915 - I don't believe this is the recommended implementation described in the issue.

**Comment by chinmayb** [comment]
> If  the user did not set any EA in the object, then the search would not include EA
Yes.  Currently if only EA is set and user calls "Getobject" method EAs are not included for searching.  Because `EASearch` field needs to be filled. EA field is specific to an object unlike easearch which is a part of IBBase.

**Comment by yuewko** [comment]
Removing EaSearch would not lead to client changes, since EaSearch is only used internally.

Now, for EA, the code need to be able to marshal it differently depending on whether it is used for search or set/update. If this can be achieved leaving it the way it is (i.e. just a map), that would be perfect as it wouldn't require client changes. Maybe give this more thoughts?

**Comment by chinmayb** [comment]
> Removing  EaSearch would not lead to client changes
Yes, I was referring  to  changing the EA to struct type.

**Comment by yuewko** [comment]
For backward compatibility, it would be good to leave EA just a map as it is now.

One idea is to add a "private" entry to the map to indicate whether it is used for update or search, and later on marshal it accordingly.

Of course, please consider other options. If changing to struct make it more future proof, don't write it off solely for backward compatibility reason.

**Comment by chinmayb** [comment]
A you know ea is defined as the following for an obj
`Ea     EA     `json:"extattrs,omitempty"``

so if Ea field also needs to be used for searching , it should be set empty. If not `extattrs` will be marshaled and server will error out saying "Field is not searchable: extattrs".

it'll involve more hacks for checking the method type in build body/Get object

**Comment by yuewko** [comment]
@chinmayb , I took a deep dive into this today....  I came up with a couple of workable solutions, but none of them is perfect and all require some (albeit minor) external API changes. If you are interested, I'll be more than happy to discuss this with you offline.

Also, I'm pretty sure that the `GetRecordA()` method implemented in this PR is not what @sjberman is looking for. According to his comment https://github.com/infobloxopen/infoblox-go-client/issues/48#issuecomment-374287770, he would like to specify EA **(along with other fields**). 

Unless we (meaning you ;-) ) come up with a much improved approach in the meantime, I propose closing this PR and take the time to **do it right** - since I suspect some overhaul and external API change might be inevitable.

I apologize for the prolonged back and forth.

**Comment by chinmayb** [comment]
@yuewko Yes, the PR doesn't exactly does what @sjberman wants. It provides an alternative way.  I suppose we can close this. We'll discuss this offline.

**Pull request closed without merging**
