### PR TITLE
Container support

### PR DESCRIPTION
**Pull request by yuewko**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Please squash the commits, and also update the documentation.

**Comment by johnbelamaric** [comment]
Oh, I see the docs are in the other repo. That's fine. But please squash the commits.

**Comment by yuewko** [comment]
Do you mean rebasing it against the refactor_ipam changes?

**Comment by yuewko** [comment]
I have rebased it. Please me know if this works. Thanks!!

**Pull request merged**
