### PR TITLE
Allow to use object manager for on-prem environments

### LINKED ISSUE #79: Unknown extensible attribute: Cloud API Owned
I would like to use the AllocateIP function on a on-prem infoblox environment with WAPI Version 2.3.1 but i get the error: `Unknown extensible attribute: Cloud API Owned`.
It would be nice if the object_manager functions could be used on on-prem instances as well.

### PR DESCRIPTION
**Pull request by dsbrng25b**
Fix #79

### CODE REVIEW

**Comment by saiprasannasastry** [comment]
can you run the UT's and see if it passes?

**Comment by dsbrng25b** [comment]
Yes, I can run the unit tests and they pass. You should also see that the build on travis ci was successful which means that the tests pass.

**Comment by saiprasannasastry** [comment]
I'm sorry , I meant can you write new UT's to test the particular feature

**Comment by MnrGreg** [comment]
I'm in the same boat as you @dsbrng25b. Nice work!

It would then be useful if one could set an `on-premise` flag within the TF Provider configuration of infobloxopen/terraform-provider-infoblox which toggles both the `OmitCloudAttrs` and the Cloud License check which @jpereira put together here infobloxopen/terraform-provider-infoblox#23

**Comment by jpereira** [comment]
I gave up about the Infoblox. they don't care about the users, I convinced everyone in my previous company to drop it. terrible support.

**Comment by saiprasannasastry** [comment]
Hi @MnrGreg the requirment that PM gave us was to make sure the cloud licence is require , hence the check.I will talk to them and see if they want to strip the check of. @jpereira .About this PR it is not merged because i am waiting if @dsbrng25b  to write the UT's

**Comment by dsbrng25b** [comment]
@MnrGreg @jpereira 
The initial intent of the PR was to make the terraform-provider-infoblox able to work in on-prem environments. In the mean time (almost 2 month since I opened the PR) I found another solution. 
I removed the license check form the terraform-provider-infoblox and added the follwing extensible attributes over the Infoblox admin GUI:
* VM Name
* VM ID
* Tenant ID
* CMP Type
* Cloud API Owned

That way the terraform-provider-infoblox does work for me. You can find the changes in my fork of terraform-provider-infoblox: https://github.com/dsbrng25b/terraform-provider-infoblox
Which values you then use in the Terraform config for vm_id, and tenant_id doesn't really matter. They are just set as custom attribute and as far as I understood, do have no other meaning.

@saiprasannasastry 
I no longer need the changes of this PR but they might be useful for other people who want to use the infoblox-go-client in their on-prem environments.
So if you like to add some value for your customers its up to you to write the unit tests yourself and merge the changes otherwise you can close the PR.

Concerning the license check in the infoblox-provider-terraform: Thats a thing i really don't understand. On one hand you opensource the code and then on the other hand you add this protectionist license check feature which can be removed by everyone who has basic Go know how either way.

**Comment by saiprasannasastry** [comment]
the requirment from PM team was to add the check. i will see what can be done.

**Comment by saiprasannasastry** [comment]
@dsbrng25b I am addressing changes for  #82 to provide update options for Records, if it is okay by you , i will add these changes in the new PR i will raise by EOD or tomorrow

**Comment by saiprasannasastry** [comment]
@dsbrng25b i am addressing #82 to provide update options for DNS records, and when i raise that, there might be conflict again, so i will pull this PR and add your changes as well to mine and then raise a new PR . Is that okay by you?

**Comment by codyja** [comment]
I totally agree with @dsbrng25b . The license checking is already in our infoblox on prem installation. Don't really need it in the terraform provider too.

**Comment by saiprasannasastry** [comment]
@codyja  yes will be removing the check in terraform :)

**Comment by saiprasannasastry** [comment]
@finarfin  the PR was raised specifically for terraform, and now we have removed the license check there. i know this is required but not sure if the other plugins might break, if you can locally add these changes and test at least the terraform plugin, raise a new PR/ commit to the same one should be fine by me.

**Comment by finarfin** [comment]
Thank you @saiprasannasastry. I have a bit of a different issue than @dsbrng25b; we have cloud license. Our issue is that Terraform is not a cloud adapter. Yet because of these EA; anything created by Terraform cannot be managed by non-superusers (even the user Terraform used to create it). 

`
WAPI request error: 400('400 Bad Request')
Contents:
{ "Error": "AdmConDataError: None (IBDataConflictError: IB.Data.Conflict:This object is Adapter Owned and can be modified only by Adapter or Super user.)",
  "code": "Client.Ibap.Data.Conflict",
  "text": "This object is Adapter Owned and can be modified only by Adapter or Super user."
}
`

This PR should resolve that issue. I would like to go forward with this change especially because other 2 Terraform providers built by community are not maintained anymore - because there is an official one. 

@saiprasannasastry, do you agree?

@dsbrng25b how would you like me to go forward? I can send you a PR to your fork, I can create a new PR based on your fork. Please let me know.

**Comment by saiprasannasastry** [comment]
@finarfin  this plugin is the official one, so i'd agree , like i said you can raise a new/commit to the same one :)

**Comment by saiprasannasastry** [comment]
@finarfin in your new PR, if you could figure out a way to not break any other changes that would be better

**Pull request closed without merging**
